apiVersion: apps/v1 
kind: Deployment
metadata:
  name: open5gs-smf-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-smf
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-smf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/open5gs:v2.1.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/open5gs-smfd"]
        volumeMounts:
        - name: open5gs-smfcfg
          mountPath: /open5gs/install/etc/open5gs/smf.yaml
          subPath: smf.yaml
      volumes:
      - name: open5gs-smfcfg
        configMap:
          name: open5gs-configmap
          items: 
          - key: smf.yaml
            path: smf.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf-svc
spec:
  selector:
    app: open5gs-smf
  clusterIP: None # 10.96.100.2
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
    - name: gtpc
      protocol: UDP
      port: 2123
    - name: pfcp
      protocol: UDP
      port: 8805
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf-nodeport
spec:
  type: NodePort
  selector:
    app: open5gs-smf
  ports:
  - name: pfcp
    protocol: UDP
    port: 8805
    nodePort: 8805
