apiVersion: apps/v1 
kind: Deployment
metadata:
  name: open5gs-hss-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-hss
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-hss
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/open5gs:v2.1.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/open5gs-hssd"]
        volumeMounts:
        - name: open5gs-hsscfg
          mountPath: /open5gs/install/etc/open5gs/hss.yaml
          subPath: hss.yaml
      volumes:
      - name: open5gs-hsscfg
        configMap:
          name: open5gs-configmap
          items: 
          - key: hss.yaml
            path: hss.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-hss-svc
spec:
  selector:
    app: open5gs-hss
  clusterIP: None # 10.96.100.2
  ports:
    - name: sip
      protocol: TCP
      port: 7060