apiVersion: apps/v1 
kind: Deployment
metadata:
  name: open5gs-pcf-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-pcf
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-pcf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/open5gs:v2.1.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/open5gs-pcfd"]
        volumeMounts:
        - name: open5gs-pcfcfg
          mountPath: /open5gs/install/etc/open5gs/pcf.yaml
          subPath: pcf.yaml
      volumes:
      - name: open5gs-pcfcfg
        configMap:
          name: open5gs-configmap
          items: 
          - key: pcf.yaml
            path: pcf.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcf-svc
spec:
  selector:
    app: open5gs-pcf
  clusterIP: None # 10.96.100.2
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
