apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-configmap
data:
  nrf.yaml: |
    logger:
      file:
        path: /open5gs/install/var/log/open5gs/nrf.log  # /var/log/open5gs/nrf.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    nrf:
      serving:  # 5G roaming requires PLMN in NRF
        - plmn_id:
            mcc: 999
            mnc: 70
      sbi:
        server:
          - address: open5gs-nrf-svc  # 127.0.0.10
            port: 80  # 7777

    ################################################################################
    # SBI Server
    ################################################################################
    #  o Override SBI address to be advertised to NRF
    #  sbi:
    #    server:
    #      - dev: eth0
    #        advertise: open5gs-nrf.svc.local
    #
    #  sbi:
    #    server:
    #      - address: localhost
    #        advertise:
    #          - 127.0.0.99
    #          - ::1
    #
    ################################################################################
    # HTTPS scheme with TLS
    ################################################################################
    #  o Set as default if not individually set
    #  default:
    #    tls:
    #      server:
    #        scheme: https
    #        private_key: /etc/open5gs/tls/nrf.key
    #        cert: /etc/open5gs/tls/nrf.crt
    #      client:
    #        scheme: https
    #        cacert: /etc/open5gs/tls/ca.crt
    #  sbi:
    #    server:
    #      - address: nrf.localdomain
    #
    #  o Add client TLS verification
    #  default:
    #    tls:
    #      server:
    #        scheme: https
    #        private_key: /etc/open5gs/tls/nrf.key
    #        cert: /etc/open5gs/tls/nrf.crt
    #        verify_client: true
    #        verify_client_cacert: /etc/open5gs/tls/ca.crt
    #      client:
    #        scheme: https
    #        cacert: /etc/open5gs/tls/ca.crt
    #        client_private_key: /etc/open5gs/tls/nrf.key
    #        client_cert: /etc/open5gs/tls/nrf.crt
    #  sbi:
    #    server:
    #      - address: nrf.localdomain

---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf-svc
spec:
  selector:
    app: open5gs-nrf
  clusterIP: None
  ports:
    - name: sbi
      protocol: TCP
      port: 80  # 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nrf-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-nrf
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-nrf
    spec:
      containers:
        - name: open5gs-nrf-container
          image: free5gmano/open5gs:v2.7.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args: ["-c", "sleep 5 && /open5gs-entrypoint.sh && ./install/bin/open5gs-nrfd"]
          ports:
            - containerPort: 80  # 7777
              name: sbi
              protocol: TCP
          volumeMounts:
            - name: open5gs-nrfcfg
              mountPath: /open5gs/install/etc/open5gs/nrf.yaml
              subPath: nrf.yaml
      volumes:
        - name: open5gs-nrfcfg
          configMap:
            name: open5gs-nrf-configmap
            items:
              - key: nrf.yaml
                path: nrf.yaml
