apiVersion: apps/v1 
kind: Deployment
metadata:
  name: open5gs-pcrf-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-pcrf
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-pcrf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/open5gs:v2.1.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/open5gs-pcrfd"]
        volumeMounts:
        - name: open5gs-pcrfcfg
          mountPath: /open5gs/install/etc/open5gs/pcrf.yaml
          subPath: pcrf.yaml
      volumes:
      - name: open5gs-pcrfcfg
        configMap:
          name: open5gs-configmap
          items: 
          - key: pcrf.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-ausf-svc
spec:
  selector:
    app: open5gs-ausf
  clusterIP: None # 10.96.100.2
  ports:
    - name: sctp
      protocol: SCTP
      port: 3868