apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf-svc
spec:
  selector:
    app: open5gs-nrf
  clusterIP: None # 10.96.100.2
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: open5gs-nrf-deployment
spec:
  selector:
    matchLabels:
      app: open5gs-nrf
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-nrf
    spec:
      containers:      
      - name: myapp-container
        image: free5gmano/open5gs:v2.1.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sleep 10s && ./bin/open5gs-nrfd"]
        volumeMounts:
        - name: open5gs-nrfcfg
          mountPath: /open5gs/install/etc/open5gs/nrf.yaml
          subPath: nrf.yaml
      volumes:
      - name: open5gs-nrfcfg
        configMap:
          name: open5gs-configmap
          items: 
          - key: nrf.yaml
            path: nrf.yaml


